# Generated by Django 4.2 on 2026-06-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanchonete',
            name='estoque',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lanchonete',
            name='preço',
            field=models.IntegerField(max_length=10),
        ),
    ]
