# Generated by Django 4.2 on 2026-06-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanch', '0002_alter_lanchonete_estoque_alter_lanchonete_preço'),
    ]

    operations = [
        migrations.AddField(
            model_name='aulas',
            name='filas',
            field=models.IntegerField(default=0),
        ),
    ]
