# Generated by Django 4.2 on 2026-06-13 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lanch', '0003_aulas_filas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lanchonete',
            new_name='loja',
        ),
        migrations.RenameField(
            model_name='loja',
            old_name='salgado',
            new_name='produtos',
        ),
    ]
